modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="playerscreenevent"
version="1.0.0"
displayName="Player Screen Event"
authors="LAYON, NegativeStudios"
description='''Full-screen waiting room overlay controlled from the server with /playerscreen show and /playerscreen hide.'''

[[dependencies.playerscreenevent]]
modId="forge"
mandatory=true
versionRange="[47.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.playerscreenevent]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
